export const publicRoutes = [
  { path: '/platform/features', pageKey: 'features' },
  { path: '/platform/dashboard', pageKey: 'dashboard' },
  { path: '/platform/ai-engine', pageKey: 'ai-engine' },
  { path: '/platform/integrations', pageKey: 'integrations' },
  { path: '/platform/pricing', pageKey: 'pricing' },
  { path: '/platform/usage', pageKey: 'usage' },
  { path: '/solutions/developers', pageKey: 'developers' },
  { path: '/solutions/security-teams', pageKey: 'security-teams' },
  { path: '/solutions/enterprises', pageKey: 'enterprises' },
  { path: '/solutions/universities', pageKey: 'universities' },
  { path: '/solutions/agencies', pageKey: 'agencies' },
  { path: '/resources/documentation', pageKey: 'documentation' },
  { path: '/resources/api-reference', pageKey: 'api-reference' },
  { path: '/resources/learning-center', pageKey: 'learning-center' },
  { path: '/resources/blog', pageKey: 'blog' },
  { path: '/customers/testimonials', pageKey: 'testimonials' },
  { path: '/resources/case-studies', pageKey: 'case-studies' },
  { path: '/resources/release-notes', pageKey: 'release-notes' },
  { path: '/resources/roadmap', pageKey: 'roadmap' },
  { path: '/developers/sdks', pageKey: 'sdks' },
  { path: '/developers/rest-api', pageKey: 'rest-api' },
  { path: '/developers/cli', pageKey: 'cli' },
  { path: '/developers/github-integration', pageKey: 'github-integration' },
  { path: '/developers/webhooks', pageKey: 'webhooks' },
  { path: '/company/about', pageKey: 'about' },
  { path: '/company/mission', pageKey: 'mission' },
  { path: '/company/vision', pageKey: 'vision' },
  { path: '/company/careers', pageKey: 'careers' },
  { path: '/company/partners', pageKey: 'partners' },
  { path: '/company/locations', pageKey: 'locations' },
  { path: '/company/contact', pageKey: 'contact' },
  { path: '/support/help-center', pageKey: 'help-center' },
  { path: '/support/faq', pageKey: 'support-faq' },
  { path: '/support/status', pageKey: 'status' },
  { path: '/support/community', pageKey: 'community' },
  { path: '/legal/privacy-policy', pageKey: 'privacy-policy' },
  { path: '/legal/terms', pageKey: 'terms' },
  { path: '/legal/cookie-policy', pageKey: 'cookie-policy' },
  { path: '/legal/responsible-disclosure', pageKey: 'responsible-disclosure' },
  { path: '/legal/security-commitment', pageKey: 'security-commitment' },
  { path: '/legal/compliance', pageKey: 'compliance' },
];

export const footerGroups = [
  {
    title: 'Platform',
    links: [
      { label: 'Features', to: '/platform/features' },
      { label: 'Dashboard', to: '/platform/dashboard' },
      { label: 'AI Engine', to: '/platform/ai-engine' },
      { label: 'Integrations', to: '/platform/integrations' },
      { label: 'Usage', to: '/platform/usage' },
      { label: 'Pricing', to: '/platform/pricing' },
    ],
  },
  {
    title: 'Solutions',
    links: [
      { label: 'Developers', to: '/solutions/developers' },
      { label: 'Security Teams', to: '/solutions/security-teams' },
      { label: 'Enterprises', to: '/solutions/enterprises' },
      { label: 'Universities', to: '/solutions/universities' },
      { label: 'Agencies', to: '/solutions/agencies' },
    ],
  },
  {
    title: 'Resources',
    links: [
      { label: 'Documentation', to: '/resources/documentation' },
      { label: 'API Reference', to: '/resources/api-reference' },
      { label: 'Learning Center', to: '/resources/learning-center' },
      { label: 'Blog', to: '/resources/blog' },
      { label: 'Testimonials', to: '/customers/testimonials' },
      { label: 'Case Studies', to: '/resources/case-studies' },
      { label: 'Release Notes', to: '/resources/release-notes' },
      { label: 'Roadmap', to: '/resources/roadmap' },
    ],
  },
  {
    title: 'Developers',
    links: [
      { label: 'SDKs', to: '/developers/sdks' },
      { label: 'REST API', to: '/developers/rest-api' },
      { label: 'CLI', to: '/developers/cli' },
      { label: 'GitHub Integration', to: '/developers/github-integration' },
      { label: 'Webhooks', to: '/developers/webhooks' },
    ],
  },
  {
    title: 'Company',
    links: [
      { label: 'About', to: '/company/about' },
      { label: 'Mission', to: '/company/mission' },
      { label: 'Vision', to: '/company/vision' },
      { label: 'Careers', to: '/company/careers' },
      { label: 'Partners', to: '/company/partners' },
      { label: 'Locations', to: '/company/locations' },
      { label: 'Contact', to: '/company/contact' },
    ],
  },
  {
    title: 'Support',
    links: [
      { label: 'Help Center', to: '/support/help-center' },
      { label: 'FAQ', to: '/support/faq' },
      { label: 'Status', to: '/support/status' },
      { label: 'Community', to: '/support/community' },
    ],
  },
  {
    title: 'Legal',
    links: [
      { label: 'Privacy Policy', to: '/legal/privacy-policy' },
      { label: 'Terms', to: '/legal/terms' },
      { label: 'Cookie Policy', to: '/legal/cookie-policy' },
      { label: 'Responsible Disclosure', to: '/legal/responsible-disclosure' },
      { label: 'Security Commitment', to: '/legal/security-commitment' },
      { label: 'Compliance', to: '/legal/compliance' },
    ],
  },
];

const standardFaq = [
  {
    q: 'How quickly can a team get value from Vulnexus?',
    a: 'Most teams connect their first asset, launch a scan, and review prioritized remediation guidance within the first session. The onboarding flow is built for fast proof, not ceremony.',
  },
  {
    q: 'Does Vulnexus fit both security and engineering workflows?',
    a: 'Yes. Security teams get risk visibility and governance, while developers get actionable findings, contextual fixes, and APIs that plug into delivery pipelines.',
  },
  {
    q: 'Can the platform scale beyond a small team?',
    a: 'Vulnexus is designed for distributed ownership. Role-based access, shared workspaces, audit trails, and automation keep enterprise programs coordinated without slowing delivery.',
  },
];

const standardFooter = {
  title: 'Explore the full platform',
  copy: 'Use the navigation hub below to move between product, solution, developer, and trust pages.',
};

const standardHighlights = [
  {
    title: 'Operational clarity',
    text: 'Every page explains what the system does, why it matters, and how teams use it in practice.',
  },
  {
    title: 'Security-first design',
    text: 'Premium surfaces, strong hierarchy, and calm motion keep the experience trustworthy and fast to read.',
  },
  {
    title: 'Built for adoption',
    text: 'The interface is structured for executives, operators, and developers without changing the visual language.',
  },
];

const standardTimeline = [
  { step: '01', title: 'Discover the surface', text: 'Map assets, owners, integrations, and the remediation flow in a single view.' },
  { step: '02', title: 'Prioritize what matters', text: 'Use risk scoring, exploit context, and compliance impact to sequence the work.' },
  { step: '03', title: 'Resolve with confidence', text: 'Track ownership, verify fixes, and keep leadership informed with clean reporting.' },
];

const standardStats = [
  { label: 'Audit-ready visibility', value: '100%' },
  { label: 'Teams onboarded faster', value: '4x' },
  { label: 'Reporting cycles reduced', value: '68%' },
];

function makeStandardPage({
  eyebrow,
  title,
  lead,
  intro,
  spotlight,
  primaryCta = { label: 'Start free trial', to: '/signup' },
  secondaryCta = { label: 'View dashboard', to: '/dashboard' },
  featureTitle = 'What this page helps teams understand',
  featureCopy = 'This destination is part of the wider Vulnexus operating experience and follows the same premium design language.',
  highlights = standardHighlights,
  timeline = standardTimeline,
  faq = standardFaq,
  stats = standardStats,
  footer = standardFooter,
}) {
  return {
    eyebrow,
    title,
    lead,
    intro,
    spotlight,
    primaryCta,
    secondaryCta,
    featureTitle,
    featureCopy,
    highlights,
    timeline,
    faq,
    stats,
    footer,
  };
}

export const marketingPages = {
  landing: {
    eyebrow: 'Luxury AI security operating system',
    title: 'Vulnexus turns vulnerability management into a calm, premium control surface.',
    lead: 'Built for security leaders, developers, and operators who want precise signal, confident remediation, and a product experience that feels worthy of the programs it runs.',
    intro: 'The V2 experience replaces noisy cyber theatrics with a refined operating rhythm: gold on graphite, measured motion, and highly legible intelligence.',
    spotlight: 'Trusted by teams that need executive visibility without losing the technical depth required to ship fixes.',
    primaryCta: { label: 'Launch the dashboard', to: '/login' },
    secondaryCta: { label: 'Explore the platform', to: '/platform/features' },
    heroStats: [
      { label: 'Assets monitored', value: '48k+' },
      { label: 'Issues triaged daily', value: '11k+' },
      { label: 'Risk reduction window', value: '72 hrs' },
      { label: 'Signal-to-noise lift', value: '3.8x' },
    ],
    trustedBy: ['Northstar Financial', 'Helix Cloud', 'Arcadia Health', 'Talon Labs', 'Aster Forge', 'Nexus University'],
    why: {
      title: 'Why Vulnexus exists',
      copy: 'Security teams do not need louder dashboards. They need a system that shortens decision time, reduces ambiguity, and keeps the organization moving with a shared understanding of risk.',
      cards: [
        { title: 'Decision support, not data noise', text: 'Normalize scan output into prioritized actions the business can actually absorb.' },
        { title: 'Executive clarity', text: 'Translate technical findings into risk narratives leadership can compare across quarters.' },
        { title: 'Developer-friendly remediation', text: 'Attach context, fix paths, and ownership cues so findings do not stall in handoff.' },
      ],
    },
    engine: {
      title: 'AI Security Engine',
      copy: 'The engine combines deterministic rule checks, model-assisted ranking, asset context, and workflow signals to produce a single remediation queue that is fast, explainable, and easy to govern.',
      metrics: [
        { label: 'Risk ranking latency', value: '< 2s' },
        { label: 'Policy rules applied', value: '420+' },
        { label: 'Context sources fused', value: '12' },
      ],
      cards: [
        { title: 'Adaptive triage', text: 'Classifies findings by exploitability, ownership, and likely business impact.' },
        { title: 'Explainable priorities', text: 'Every score can be traced back to evidence, not just a black-box label.' },
        { title: 'Workflow memory', text: 'Learns what your team closes quickly and what should escalate sooner.' },
      ],
    },
    features: [
      { title: 'Deep scanning', text: 'Covers code, cloud, infrastructure, repositories, and web surfaces from a single queue.' },
      { title: 'Governance', text: 'Role controls, approval chains, and audit-safe reporting keep accountability crisp.' },
      { title: 'Automation', text: 'Trigger remediations, ticketing, and follow-up checks without leaving the platform.' },
      { title: 'Observability', text: 'See trends, regressions, ownership patterns, and remediation velocity over time.' },
      { title: 'Collaboration', text: 'Security, engineering, and compliance work from the same shared map of risk.' },
      { title: 'Integrations', text: 'Connect to GitHub, CI pipelines, alerting tools, and operational systems cleanly.' },
    ],
    capabilities: [
      { title: 'Dashboard cockpit', text: 'A premium operating view that surfaces risk, throughput, and ownership in one place.' },
      { title: 'Threat intelligence', text: 'Correlation across CVEs, asset history, and exploit signals to sharpen prioritization.' },
      { title: 'Continuous verification', text: 'Retest, confirm, and close the loop so fixes stay fixed.' },
      { title: 'Compliance ready', text: 'Structured evidence and reporting that help programs stay audit prepared all year.' },
    ],
    how: [
      { step: '01', title: 'Connect the environment', text: 'Add assets, repositories, cloud accounts, and critical apps with minimal setup.' },
      { step: '02', title: 'Scan and score', text: 'The engine analyzes exposure, context, and potential blast radius in parallel.' },
      { step: '03', title: 'Assign and remediate', text: 'Route the right findings to the right teams with clear ownership and due dates.' },
      { step: '04', title: 'Verify and report', text: 'Close the loop with retests, executive summaries, and trend reporting.' },
    ],
    dashboard: {
      title: 'Dashboard showcase',
      copy: 'The operating cockpit is designed to feel like premium infrastructure software: dense where it matters, calm where it does not, and always clear about what needs attention next.',
      panels: [
        { title: 'Risk posture', value: 'Medium', detail: 'Six critical items, fifteen high priority items, and a stable compliance baseline.' },
        { title: 'Remediation velocity', value: '+28%', detail: 'Median time to close dropped as automation and ownership signals improved.' },
        { title: 'Live scan queue', value: '14 active', detail: 'Parallel jobs are being processed across code, cloud, and web assets.' },
      ],
    },
    stats: [
      { label: 'Program leaders', value: '2.5k+' },
      { label: 'Monthly scans', value: '480k+' },
      { label: 'Findings remediated', value: '91%' },
      { label: 'Uptime', value: '99.99%' },
    ],
    testimonials: [
      { name: 'Alicia Morgan', role: 'CISO, Northstar Financial', text: 'Vulnexus reads like the kind of platform you trust in a board meeting and still enjoy using at midnight.' },
      { name: 'Dev Patel', role: 'VP Platform Engineering, Helix Cloud', text: 'The triage quality is strong enough that our engineers stopped arguing about the queue and started fixing it.' },
      { name: 'Mina Okafor', role: 'Security Operations Lead, Arcadia Health', text: 'It feels premium, but more importantly it feels precise. That combination is rare in security software.' },
    ],
    roadmap: [
      { milestone: 'Q3', title: 'Cross-asset ownership graph', text: 'Map services, repos, teams, and remediation dependencies into one graph.' },
      { milestone: 'Q4', title: 'Predictive exposure trends', text: 'Forecast where risk will cluster before backlog pressure builds.' },
      { milestone: 'Q1', title: 'Autonomous policy packs', text: 'Ship reusable security playbooks that adapt to team maturity and scale.' },
    ],
    faq: [
      { q: 'Is the experience optimized for executives and operators?', a: 'Yes. The information hierarchy is intentionally layered so each audience sees the depth they need without extra clutter.' },
      { q: 'Does Vulnexus support continuous workflows?', a: 'The platform is designed for continuous scanning, triage, and verification rather than one-off assessments.' },
      { q: 'Can teams use it without sacrificing design polish?', a: 'That is the point of V2: the interface is intended to feel like enterprise software, not an internal prototype.' },
    ],
    footer: {
      title: 'A premium control hub for security programs',
      copy: 'Everything below is available from the footer navigation and mirrors the structure of the public site.',
    },
  },
  features: makeStandardPage({
    eyebrow: 'Platform features',
    title: 'Features that move Vulnexus from scanning tool to operating system.',
    lead: 'The platform is composed around high-confidence workflows: discovery, prioritization, ownership, verification, and reporting.',
    intro: 'Each feature section is built to explain what it does, why it matters, and how it fits the lifecycle of a serious security program.',
    spotlight: 'Use this page to understand the breadth of the platform without losing the simplicity of the product story.',
    featureTitle: 'Core capability set',
    featureCopy: 'These features are arranged to support adoption across security, engineering, and leadership audiences.',
    highlights: [
      { title: 'Precision scanning', text: 'Find issues across apps, repositories, and infrastructure without drowning teams in duplicate noise.' },
      { title: 'Risk orchestration', text: 'Move from detection to prioritization to remediation with fewer handoffs.' },
      { title: 'Board-ready reporting', text: 'Summaries are shaped for the people who need to make decisions, not just inspect data.' },
    ],
  }),
  dashboard: makeStandardPage({
    eyebrow: 'Dashboard',
    title: 'A cockpit that turns exposure into an operational story.',
    lead: 'The dashboard page explains how the platform condenses the whole program into a fast, elegant command surface.',
    intro: 'The dashboard is intentionally dense in signal and restrained in ornament. It should feel like a premium instrument panel, not a noisy chart wall.',
    spotlight: 'Built for daily use by security operations, platform engineering, and leadership teams.',
    featureTitle: 'What lives in the cockpit',
    featureCopy: 'The dashboard brings together current risk, trend shifts, ownership, and action queues in one place.',
  }),
  'ai-engine': makeStandardPage({
    eyebrow: 'AI engine',
    title: 'Explainable machine intelligence for security triage.',
    lead: 'The AI engine page describes how Vulnexus ranks, groups, and recommends without making the product feel opaque.',
    intro: 'This is not AI for novelty. It is AI as a force multiplier for precision, governance, and speed.',
    spotlight: 'The model layer is tuned to help teams understand why a finding matters and what to do next.',
    featureTitle: 'Engine principles',
    featureCopy: 'Risk ranking should be explainable, repeatable, and easy to audit. The page mirrors that philosophy.',
  }),
  integrations: makeStandardPage({
    eyebrow: 'Integrations',
    title: 'Connect the systems your teams already use.',
    lead: 'Integration coverage spans source control, CI/CD, messaging, ticketing, and cloud workflows.',
    intro: 'The integration story is designed to reassure technical buyers that Vulnexus fits the stack they already trust.',
    spotlight: 'The platform favors open, reliable interfaces over brittle one-off connectors.',
    featureTitle: 'Integration surfaces',
    featureCopy: 'Link the platform into delivery and response systems so findings reach the right owner with minimal delay.',
  }),
  pricing: makeStandardPage({
    eyebrow: 'Pricing',
    title: 'Plans built for teams that want value, clarity, and scale.',
    lead: 'Pricing should feel straightforward, premium, and easy to compare. The page balances trial access with enterprise confidence.',
    intro: 'A public pricing page keeps the experience transparent while still supporting the internal billing screen used in the app shell.',
    spotlight: 'The product surface stays calm whether a buyer is exploring pricing or a customer is upgrading inside the app.',
    featureTitle: 'How plans are framed',
    featureCopy: 'The page explains capability tiers, support depth, and the path from trial to enterprise deployment.',
  }),
  usage: makeStandardPage({
    eyebrow: 'Usage',
    title: 'Practical usage paths for teams adopting Vulnexus.',
    lead: 'The usage page shows how visitors can move from a first scan to recurring security operations without guessing what comes next.',
    intro: 'This destination gives prospects and new users a plain-language map of common workflows, ownership patterns, and daily operating habits.',
    spotlight: 'Helpful for evaluators who want to understand how the platform fits real work.',
    featureTitle: 'Usage paths',
    featureCopy: 'First scan, recurring monitoring, remediation ownership, reporting, and verification are framed as connected workflows.',
  }),
  developers: makeStandardPage({
    eyebrow: 'Developers',
    title: 'A developer experience that respects implementation detail.',
    lead: 'This page frames Vulnexus as a platform with strong APIs, automation hooks, and documentation built for real teams.',
    intro: 'Security tooling often fails developers by hiding the implementation path. Vulnexus exposes the right level of control.',
    spotlight: 'It should feel easy to build with and hard to outgrow.',
    featureTitle: 'What developers get',
    featureCopy: 'SDKs, REST APIs, CLI workflows, and repository integrations are organized to support product teams and platform engineers.',
  }),
  'security-teams': makeStandardPage({
    eyebrow: 'Security teams',
    title: 'Built for security operators who need prioritization and governance.',
    lead: 'Security leaders need confidence that the product will support policy, ownership, and reporting without extra overhead.',
    intro: 'This page is the buyer-facing argument for teams that run vulnerability management as an ongoing program.',
    spotlight: 'It emphasizes governance, visibility, and accountability over flashy visuals.',
    featureTitle: 'Team outcomes',
    featureCopy: 'Faster triage, better ownership, cleaner reporting, and more reliable remediation loops.',
  }),
  enterprises: makeStandardPage({
    eyebrow: 'Enterprises',
    title: 'Enterprise-grade control for distributed organizations.',
    lead: 'Enterprise buyers want scale, auditability, and consistency across many business units and cloud estates.',
    intro: 'The page presents Vulnexus as an operating standard rather than a point solution.',
    spotlight: 'The story centers on governance, integrations, and executive visibility.',
    featureTitle: 'Enterprise priorities',
    featureCopy: 'Access controls, reporting, workflow segmentation, and audit trails are the main focus.',
  }),
  universities: makeStandardPage({
    eyebrow: 'Universities',
    title: 'Teach secure engineering with a platform that mirrors the real world.',
    lead: 'Academic teams need something sophisticated enough for labs and practical enough for faculty and students.',
    intro: 'The page highlights learning, experimentation, and security literacy without dumbing down the platform.',
    spotlight: 'Designed to support research environments, labs, and capstone security work.',
    featureTitle: 'Academic use cases',
    featureCopy: 'Course labs, student projects, departmental visibility, and policy education.',
  }),
  agencies: makeStandardPage({
    eyebrow: 'Agencies',
    title: 'A scalable delivery model for consultancies and managed security partners.',
    lead: 'Agencies need multi-client structure, branded reporting, and a clean operational handoff.',
    intro: 'The page speaks to service providers managing many customer environments at once.',
    spotlight: 'The platform has to feel organized enough to trust with multiple client portfolios.',
    featureTitle: 'Agency workflows',
    featureCopy: 'Client segmentation, reporting speed, and repeatable engagement patterns are the core messages.',
  }),
  documentation: makeStandardPage({
    eyebrow: 'Documentation',
    title: 'Documentation that helps teams move from discovery to implementation.',
    lead: 'A premium documentation page should feel precise, calm, and practical.',
    intro: 'The page frames docs as the fastest way to go from evaluation to a production workflow.',
    spotlight: 'Use it to orient operators, admins, and developers before they touch the platform.',
    featureTitle: 'Docs structure',
    featureCopy: 'Concepts, setup, workflows, and reference material are organized for fast scanning.',
  }),
  'api-reference': makeStandardPage({
    eyebrow: 'API reference',
    title: 'A reference surface for integrations and automation.',
    lead: 'The API page explains endpoints, event flows, and integration patterns in a way that feels reliable and complete.',
    intro: 'Good API docs reduce support burden and increase adoption. The page is tuned around that goal.',
    spotlight: 'Useful for teams wiring Vulnexus into internal tools and delivery pipelines.',
    featureTitle: 'API priorities',
    featureCopy: 'Authentication, pagination, webhooks, error handling, and event semantics.',
  }),
  'learning-center': makeStandardPage({
    eyebrow: 'Learning center',
    title: 'A structured learning path for new and advanced users.',
    lead: 'The learning center balances introduction, practical examples, and deeper best-practice material.',
    intro: 'It is designed to help teams adopt the platform with confidence rather than trial-and-error.',
    spotlight: 'Helpful for onboarding, enablement, and ongoing security maturity.',
    featureTitle: 'Learning themes',
    featureCopy: 'Getting started, workflow mastery, and advanced operational patterns.',
  }),
  blog: makeStandardPage({
    eyebrow: 'Blog',
    title: 'A thoughtful place for product stories, security insights, and release context.',
    lead: 'The blog page gives the brand a voice that feels expert without being noisy.',
    intro: 'Write here about product design, programmatic security, threat trends, and release thinking.',
    spotlight: 'The visual tone should feel editorial and premium.',
    featureTitle: 'Editorial lanes',
    featureCopy: 'Product thinking, security analysis, and customer stories.',
  }),
  testimonials: makeStandardPage({
    eyebrow: 'Testimonials',
    title: 'Customer stories from teams turning security signal into action.',
    lead: 'A dedicated testimonials page gives social proof its own destination instead of burying it in the landing page.',
    intro: 'Use this page to collect quotes, outcomes, and short narratives from security leaders, developers, and operators.',
    spotlight: 'Useful for trust-building during evaluation and procurement.',
    featureTitle: 'What customers highlight',
    featureCopy: 'Cleaner triage, faster remediation, easier reporting, and a calmer security operating rhythm.',
  }),
  'case-studies': makeStandardPage({
    eyebrow: 'Case studies',
    title: 'Proof points that show measurable security and delivery outcomes.',
    lead: 'Case studies should read like serious operational wins, not marketing fluff.',
    intro: 'This page creates confidence for teams who need evidence before buying.',
    spotlight: 'Ideal for enterprise evaluations and stakeholder reviews.',
    featureTitle: 'What to show',
    featureCopy: 'Before/after metrics, operational changes, and the decision process.',
  }),
  'release-notes': makeStandardPage({
    eyebrow: 'Release notes',
    title: 'A calm changelog for teams who care about trust and continuity.',
    lead: 'Release notes should show progress without becoming hard to parse.',
    intro: 'The page sets expectations around product change, bug fixes, and platform maturity.',
    spotlight: 'A good release page reinforces reliability and active maintenance.',
    featureTitle: 'Release structure',
    featureCopy: 'New capabilities, improvements, fixes, and migration notes.',
  }),
  roadmap: makeStandardPage({
    eyebrow: 'Roadmap',
    title: 'A clear line of sight into what comes next.',
    lead: 'The roadmap page should feel strategic, not speculative.',
    intro: 'This destination makes the product feel alive while preserving credibility.',
    spotlight: 'Useful for customer trust and internal planning.',
    featureTitle: 'Roadmap focus',
    featureCopy: 'Platform depth, automation maturity, and operational control.',
  }),
  sdks: makeStandardPage({
    eyebrow: 'SDKs',
    title: 'SDKs that lower friction and keep implementation consistent.',
    lead: 'The SDK page tells developers what they can build quickly and safely.',
    intro: 'It should feel like a platform designed to be extended.',
    spotlight: 'Reassures teams that integration is first-class.',
    featureTitle: 'SDK goals',
    featureCopy: 'Ease of use, consistency, and coverage across major workflows.',
  }),
  'rest-api': makeStandardPage({
    eyebrow: 'REST API',
    title: 'A clean API layer for workflows, data, and automation.',
    lead: 'This page describes how to read, write, and orchestrate data through the platform.',
    intro: 'The emphasis is on predictable contracts and reliable operations.',
    spotlight: 'For teams who want direct control without losing governance.',
    featureTitle: 'REST principles',
    featureCopy: 'Consistency, clarity, and strong auth boundaries.',
  }),
  cli: makeStandardPage({
    eyebrow: 'CLI',
    title: 'Fast workflows for engineers who live in terminals.',
    lead: 'The CLI page highlights speed, portability, and scriptability.',
    intro: 'It supports teams who want to embed security checks into daily habits.',
    spotlight: 'Best for automation-heavy and developer-led organizations.',
    featureTitle: 'CLI benefits',
    featureCopy: 'Repeatable commands, script-friendly output, and easy CI integration.',
  }),
  'github-integration': makeStandardPage({
    eyebrow: 'GitHub integration',
    title: 'Bring findings directly into the code review flow.',
    lead: 'The GitHub integration page shows how Vulnexus fits developer workflows without interruption.',
    intro: 'Findings should meet engineers where they already work.',
    spotlight: 'Ideal for PR workflows, checks, and issue routing.',
    featureTitle: 'GitHub outcomes',
    featureCopy: 'Pull request context, repository mapping, and issue creation.',
  }),
  webhooks: makeStandardPage({
    eyebrow: 'Webhooks',
    title: 'Event-driven automation for security programs.',
    lead: 'Webhooks make the platform feel alive in the larger operating ecosystem.',
    intro: 'The page explains how events travel from detection to downstream systems.',
    spotlight: 'Useful for teams building internal automation and alerting.',
    featureTitle: 'Webhook events',
    featureCopy: 'Scan completion, risk changes, ownership updates, and closure signals.',
  }),
  about: makeStandardPage({
    eyebrow: 'About',
    title: 'A product company building a premium security operating system.',
    lead: 'The about page should make the mission feel clear, credible, and human.',
    intro: 'We are focused on making security work feel more precise and less chaotic.',
    spotlight: 'Use it to explain the company and the standard behind the product.',
    featureTitle: 'Company perspective',
    featureCopy: 'Clarity, craftsmanship, and trust are central to the brand.',
  }),
  mission: makeStandardPage({
    eyebrow: 'Mission',
    title: 'Make security operations more intelligent and less burdensome.',
    lead: 'The mission page turns philosophy into product direction.',
    intro: 'It exists to show why the product is built the way it is.',
    spotlight: 'A useful page for values, investors, and customers alike.',
    featureTitle: 'Mission pillars',
    featureCopy: 'Precision, accountability, and momentum.',
  }),
  vision: makeStandardPage({
    eyebrow: 'Vision',
    title: 'A future where every team can manage risk with confidence.',
    lead: 'The vision page articulates what long-term excellence looks like.',
    intro: 'It should feel aspirational without drifting into marketing fog.',
    spotlight: 'Frames the product as a category-defining operating system.',
    featureTitle: 'Vision themes',
    featureCopy: 'Automation, explainability, and operational maturity.',
  }),
  careers: makeStandardPage({
    eyebrow: 'Careers',
    title: 'Build a product that serious security teams want to use every day.',
    lead: 'The careers page should feel like an invitation to do high-quality work.',
    intro: 'Show the craft, the bar, and the kind of people the company needs.',
    spotlight: 'A premium employer brand is part of the product story.',
    featureTitle: 'What to emphasize',
    featureCopy: 'Impact, craft, ownership, and growth.',
  }),
  partners: makeStandardPage({
    eyebrow: 'Partners',
    title: 'A partner ecosystem built for delivery, trust, and scale.',
    lead: 'The partner page describes how services, platforms, and alliances extend the product.',
    intro: 'It should reassure buyers that the company can support real deployments.',
    spotlight: 'Useful for channel, alliances, and implementation partners.',
    featureTitle: 'Partner lanes',
    featureCopy: 'Implementation, consulting, technology, and education.',
  }),
  locations: makeStandardPage({
    eyebrow: 'Locations',
    title: 'Where Vulnexus works with customers, teams, and partners.',
    lead: 'The locations page gives the company presence a real home for regional contact, office, and support information.',
    intro: 'Use it for office details, service regions, support availability, and future local contact options.',
    spotlight: 'A simple location page helps the company feel reachable and credible.',
    featureTitle: 'Location details',
    featureCopy: 'Regional availability, office contacts, support coverage, and partnership presence.',
  }),
  contact: makeStandardPage({
    eyebrow: 'Contact',
    title: 'Talk to the team that built the platform.',
    lead: 'The contact page should make next steps obvious and low-friction.',
    intro: 'Keep it clear whether the visitor wants sales, support, or a partnership conversation.',
    spotlight: 'Every serious SaaS product needs a contact page that feels confident and responsive.',
    featureTitle: 'Contact options',
    featureCopy: 'Sales, support, partnerships, and press.',
  }),
  'help-center': makeStandardPage({
    eyebrow: 'Help center',
    title: 'Fast answers for users who need to keep moving.',
    lead: 'The help center keeps support self-serve, searchable, and calm.',
    intro: 'It should feel like a well-organized operations manual, not a dumping ground.',
    spotlight: 'Supports onboarding and day-to-day use.',
    featureTitle: 'Help center scope',
    featureCopy: 'Setup, workflows, troubleshooting, and account management.',
  }),
  'support-faq': makeStandardPage({
    eyebrow: 'FAQ',
    title: 'Answers to the questions teams ask before they commit.',
    lead: 'A focused FAQ page reduces friction and improves buyer confidence.',
    intro: 'The tone should be direct, honest, and concise.',
    spotlight: 'Useful for both evaluation and onboarding.',
    featureTitle: 'FAQ themes',
    featureCopy: 'Security, implementation, billing, and support.',
  }),
  status: makeStandardPage({
    eyebrow: 'Status',
    title: 'Operational transparency for the platform and its services.',
    lead: 'The status page should signal reliability and active monitoring.',
    intro: 'This destination is a trust anchor for customers and internal teams.',
    spotlight: 'Designed to be calm, direct, and legible at a glance.',
    featureTitle: 'Status information',
    featureCopy: 'Uptime, incidents, maintenance, and component health.',
  }),
  community: makeStandardPage({
    eyebrow: 'Community',
    title: 'A place for practitioners to share, learn, and build together.',
    lead: 'The community page should feel welcoming but still aligned to the product’s premium tone.',
    intro: 'Use it to support users, advocates, and integrators.',
    spotlight: 'Great for support deflection and product loyalty.',
    featureTitle: 'Community lanes',
    featureCopy: 'Events, forums, shared playbooks, and product feedback.',
  }),
  'privacy-policy': makeStandardPage({
    eyebrow: 'Privacy policy',
    title: 'Clear, readable policy language that supports trust.',
    lead: 'Legal pages should be as polished as the rest of the product.',
    intro: 'Use the page to communicate data handling practices with calm precision.',
    spotlight: 'Built to reassure buyers and procurement teams.',
    featureTitle: 'Policy themes',
    featureCopy: 'Data use, retention, control, and user rights.',
  }),
  terms: makeStandardPage({
    eyebrow: 'Terms',
    title: 'Straightforward terms that set expectations clearly.',
    lead: 'Good legal pages help the product feel mature and dependable.',
    intro: 'The page should be easy to navigate and not feel like an afterthought.',
    spotlight: 'A strong terms page helps enterprise trust reviews move faster.',
    featureTitle: 'Terms themes',
    featureCopy: 'Service scope, responsibilities, acceptable use, and limitations.',
  }),
  'cookie-policy': makeStandardPage({
    eyebrow: 'Cookie policy',
    title: 'A concise explanation of how browsing data is used.',
    lead: 'The cookie policy should be plain, direct, and respectful.',
    intro: 'It belongs in the trust story because it shows care for user privacy.',
    spotlight: 'Keep it understandable for both technical and non-technical readers.',
    featureTitle: 'Cookie themes',
    featureCopy: 'Tracking, preferences, analytics, and consent.',
  }),
  'responsible-disclosure': makeStandardPage({
    eyebrow: 'Responsible disclosure',
    title: 'A security process that invites scrutiny the right way.',
    lead: 'Responsible disclosure is part of the brand promise for a security company.',
    intro: 'The page should make it easy for researchers to report issues safely and confidently.',
    spotlight: 'Important for trust with security researchers and customers.',
    featureTitle: 'Disclosure themes',
    featureCopy: 'Scope, reporting path, timelines, and safe harbor.',
  }),
  'security-commitment': makeStandardPage({
    eyebrow: 'Security commitment',
    title: 'A public statement about how the product is built and operated securely.',
    lead: 'This page tells customers that security is not a side note.',
    intro: 'The tone should be specific, not generic.',
    spotlight: 'Reinforces due diligence for enterprise buyers.',
    featureTitle: 'Commitment themes',
    featureCopy: 'Governance, hardening, access controls, and incident response.',
  }),
  compliance: makeStandardPage({
    eyebrow: 'Compliance',
    title: 'A simple map of the controls and standards that matter.',
    lead: 'The compliance page should help customers understand how the platform supports their obligations.',
    intro: 'Use it to organize evidence, shared responsibility, and current posture.',
    spotlight: 'Designed for procurement, audit, and leadership review.',
    featureTitle: 'Compliance themes',
    featureCopy: 'Controls, attestations, evidence, and governance.',
  }),
  'support-faq-public': makeStandardPage({
    eyebrow: 'FAQ',
    title: 'Answers for public site visitors and evaluating teams.',
    lead: 'This is the public-facing question set used by the footer navigation.',
    intro: 'It keeps the tone direct and helpful.',
    spotlight: 'Use it when visitors want a fast overview before contacting sales.',
    featureTitle: 'FAQ themes',
    featureCopy: 'Setup, onboarding, security, billing, and support.',
  }),
};

export function getPublicPage(pageKey) {
  return marketingPages[pageKey] || marketingPages.features;
}
